"""LabCare — PDF service reports & trend reports (ReportLab)."""
import io
from database import now_dt

from reportlab.lib import colors
from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (BaseDocTemplate, Frame, PageTemplate, Paragraph,
                                Spacer, Table, TableStyle, HRFlowable)

BRAND = HexColor("#0F766E")
BRAND_DARK = HexColor("#134E4A")
INK = HexColor("#0F172A")
SOFT = HexColor("#64748B")
LINE = HexColor("#E2E8F0")
BG = HexColor("#F8FAFC")

styles = getSampleStyleSheet()
H1 = ParagraphStyle("H1x", parent=styles["Title"], fontSize=18, leading=24, textColor=INK, spaceAfter=2)
SUB = ParagraphStyle("SUBx", parent=styles["Normal"], fontSize=9, leading=13, textColor=SOFT)
H2 = ParagraphStyle("H2x", parent=styles["Heading2"], fontSize=11, leading=15, textColor=BRAND, spaceBefore=14, spaceAfter=5)
BODY = ParagraphStyle("BODYx", parent=styles["Normal"], fontSize=9.5, leading=14, textColor=INK)


def _header_footer(canvas, doc):
    canvas.saveState()
    w, h = A4
    # header band
    canvas.setFillColor(BRAND_DARK)
    canvas.rect(0, h - 26 * mm, w, 26 * mm, stroke=0, fill=1)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 13)
    canvas.drawString(16 * mm, h - 16 * mm, "LabCare")
    canvas.setFont("Helvetica", 8)
    canvas.drawString(16 * mm, h - 21 * mm, "Customer Complaints & Equipment Breakdowns")
    # footer
    canvas.setFillColor(SOFT)
    canvas.setFont("Helvetica", 7.5)
    canvas.drawString(16 * mm, 10 * mm, "Generated by LabCare on " + now_dt().strftime("%d %b %Y, %H:%M (MYT)"))
    canvas.drawRightString(w - 16 * mm, 10 * mm, f"Page {doc.page}")
    canvas.restoreState()


def _page(extra_flowables=None):
    frame = Frame(16 * mm, 16 * mm, A4[0] - 32 * mm, A4[1] - 48 * mm, id="f")
    flow = [Spacer(1, 26 * mm)]
    if extra_flowables:
        flow.extend(extra_flowables)
    return PageTemplate(id="p", frames=[frame], onPage=_header_footer)


def _label(text):
    return Paragraph(f'<font color="#64748B">{text}</font>', SUB)


def init_doc(buf, title):
    doc = BaseDocTemplate(buf, pagesize=A4, title=title, author="LabCare",
                          leftMargin=16 * mm, rightMargin=16 * mm,
                          topMargin=16 * mm, bottomMargin=16 * mm)
    doc.addPageTemplates([_page()])
    return doc


def _kv_table(pairs, widths=(42 * mm, None)):
    data = [[_label(k), Paragraph(str(v or "—"), BODY)] for k, v in pairs]
    t = Table(data, colWidths=widths)
    t.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, BG]),
        ("GRID", (0, 0), (-1, -1), 0.4, LINE),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    return t


def _status_color(status):
    return {
        "open": HexColor("#DC2626"), "in_progress": HexColor("#2563EB"),
        "resolved": HexColor("#16A34A"), "closed": HexColor("#64748B"),
        "reported": HexColor("#DC2626"), "diagnosed": HexColor("#2563EB"),
        "on_hold": HexColor("#D97706"),
    }.get(status, HexColor("#64748B"))


def status_cell(status):
    from reportlab.platypus import Table as T
    label = status.replace("_", " ").title()
    c = _status_color(status)
    p = Paragraph(f'<font color="#FFFFFF"><b>{label}</b></font>',
                  ParagraphStyle("s", parent=BODY, fontSize=8, leading=10))
    t = T([[p]], colWidths=[28 * mm], rowHeights=[14])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), c),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("ROUNDEDCORNERS", [5, 5, 5, 5]),
    ]))
    return t


def _log_table(comments):
    """Two-column who-said-what log, shared by both single-ticket reports."""
    rows = [[Paragraph(f'<b>{c.get("user_name", "")}</b><br/>'
                       f'<font size="7" color="#64748B">{c.get("created_at", "")}</font>', BODY),
             Paragraph(c.get("text", "") or "", BODY)] for c in comments]
    t = Table(rows, colWidths=[38 * mm, 126 * mm])
    t.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, BG]),
        ("GRID", (0, 0), (-1, -1), 0.4, LINE),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    return t


def service_report(complaint, breakdowns, comments):
    """Build a single-ticket service report PDF and return raw bytes."""
    buf = io.BytesIO()
    doc = init_doc(buf, f"Service Report {complaint.get('code', '')}")

    story = [
        Paragraph(f"Service Report — {complaint.get('code', '')}", H1),
        Paragraph(f"{complaint.get('subject', '')}", SUB),
        Spacer(1, 4),
        HRFlowable(width="100%", thickness=1, color=BRAND),
        Spacer(1, 10),
        _kv_table([
            ("Report no.", complaint.get("code")),
            ("Date issued", now_dt().strftime("%d %b %Y %H:%M (MYT)")),
            ("Organization", complaint.get("customer_name")),
            ("Equipment", complaint.get("equipment_name") or "General"),
            ("Category", complaint.get("category") or "General"),
            ("Priority", (complaint.get("priority") or "").title()),
            ("Status", (complaint.get("status") or "").replace("_", " ").title()),
            ("Reported by", complaint.get("created_by_name")),
            ("Assigned to", complaint.get("assigned_to_name") or "Unassigned"),
            ("Opened", complaint.get("created_at")),
            ("Resolved", complaint.get("resolved_at") or "—"),
        ]),
        Spacer(1, 14),
        Paragraph("Complaint description", H2),
        Paragraph(complaint.get("description") or "No description provided.", BODY),
    ]

    # breakdowns section
    story.append(Paragraph("Linked breakdown work orders", H2))
    for b in breakdowns:
        rows = [
            [status_cell(b.get("status")), Paragraph(f'<b>{b.get("code")}</b> — {b.get("equipment_name", "")}', BODY)],
            [_label("Fault"), Paragraph(b.get("fault_description", "") or "—", BODY)],
            [_label("Reported"), Paragraph(str(b.get("created_at") or "—"), BODY)],
            [_label("Root cause"), Paragraph(b.get("root_cause") or "—", BODY)],
            [_label("Resolution"), Paragraph(b.get("resolution_notes") or "—", BODY)],
        ]
        t = Table(rows, colWidths=[44 * mm, 120 * mm])
        t.setStyle(TableStyle([
            ("SPAN", (0, 0), (1, 0)),
            ("BACKGROUND", (0, 0), (-1, 0), BG),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("GRID", (0, 0), (-1, -1), 0.4, LINE),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        story.append(t)
        story.append(Spacer(1, 8))
    if not breakdowns:
        story.append(Paragraph("No breakdown work orders linked to this complaint.", BODY))

    # comments
    story.append(Paragraph("Conversation log", H2))
    story.append(_log_table(comments) if comments else Paragraph("No comments.", BODY))


    doc.build(story)
    return buf.getvalue()


def breakdown_report(breakdown, comments, source_complaint=None):
    """Build a single-breakdown service report PDF and return raw bytes.

    The breakdown counterpart of service_report(): the same LabCare letterhead,
    the same summary block and log table, then the fault, root cause,
    resolution and work log for this one work order.

    Neither ticket type carries file attachments any more — that function was
    replaced by these PDFs — so neither report has an attached-photos row.
    """
    buf = io.BytesIO()
    doc = init_doc(buf, f"Service Report {breakdown.get('code', '')}")

    equipment = breakdown.get("equipment_name") or "General"
    location = breakdown.get("location_name") or breakdown.get("department_name")

    accepted = breakdown.get("accepted_by_name")
    if accepted and breakdown.get("accepted_at"):
        accepted = f"{accepted} · {breakdown['accepted_at']}"

    # Optional rows are omitted rather than printed as a bare em-dash.
    pairs = [
        ("Report no.", breakdown.get("code")),
        ("Date issued", now_dt().strftime("%d %b %Y %H:%M (MYT)")),
        ("Organization", breakdown.get("customer_name")),
    ]
    if location:
        pairs.append(("Location/Department", location))
    pairs.append(("Equipment", equipment))
    if breakdown.get("equipment_serial"):
        pairs.append(("Serial number", breakdown["equipment_serial"]))
    pairs += [
        ("Priority", (breakdown.get("priority") or "").title()),
        ("Status", (breakdown.get("status") or "").replace("_", " ").title()),
        ("Reported by", breakdown.get("reported_by_name")),
    ]
    if breakdown.get("reporter_name"):
        pairs.append(("Reporter", breakdown["reporter_name"]))
    if breakdown.get("reporter_phone"):
        pairs.append(("Contact", breakdown["reporter_phone"]))
    pairs.append(("Assigned to", breakdown.get("assigned_to_name") or "Unassigned"))
    if accepted:
        pairs.append(("Accepted by", accepted))
    if breakdown.get("accept_reply"):
        pairs.append(("Reply to sender", f"“{breakdown['accept_reply']}”"))
    if breakdown.get("responsible_admin_name"):
        pairs.append(("Tenant admin in charge", breakdown["responsible_admin_name"]))
    pairs += [
        ("Opened", breakdown.get("created_at")),
        ("Resolved", breakdown.get("resolved_at") or "—"),
    ]
    if breakdown.get("closed_by_name"):
        pairs.append(("Resolved by", breakdown["closed_by_name"]))

    story = [
        Paragraph(f"Service Report — {breakdown.get('code', '')}", H1),
        Paragraph(f"Equipment breakdown · {equipment}", SUB),
        Spacer(1, 4),
        HRFlowable(width="100%", thickness=1, color=BRAND),
        Spacer(1, 10),
        _kv_table(pairs),
        Spacer(1, 14),
        Paragraph("Fault description", H2),
        Paragraph(breakdown.get("fault_description") or "No fault description provided.", BODY),
    ]

    # Where this work order came from, when it was raised off a complaint.
    if source_complaint:
        story.append(Paragraph("Source complaint", H2))
        story.append(Paragraph(
            f'{source_complaint.get("code", "")} — {source_complaint.get("subject", "")}', BODY))

    if breakdown.get("root_cause"):
        story.append(Paragraph("Root cause", H2))
        story.append(Paragraph(breakdown["root_cause"], BODY))

    if breakdown.get("resolution_notes"):
        story.append(Paragraph("Resolution notes", H2))
        story.append(Paragraph(breakdown["resolution_notes"], BODY))
    elif (breakdown.get("status") or "") == "resolved":
        story.append(Paragraph("Resolution notes", H2))
        story.append(Paragraph("Marked resolved with no notes recorded.", BODY))

    story.append(Paragraph("Work log", H2))
    story.append(_log_table(comments) if comments
                 else Paragraph("No work log entries.", BODY))

    doc.build(story)
    return buf.getvalue()


def trend_report(complaints, breakdowns, monthly, by_status_cmp, by_status_brk, top_equipment):
    """Build a management trend report and return raw bytes."""
    buf = io.BytesIO()
    doc = init_doc(buf, "LabCare Trend Report")

    story = [
        Paragraph("Trend &amp; Analytics Report", H1),
        Paragraph("Customer complaints &amp; equipment breakdowns", SUB),
        Spacer(1, 4),
        HRFlowable(width="100%", thickness=1, color=BRAND),
        Spacer(1, 10),
    ]

    # KPI tiles
    open_cmp = sum(1 for c in complaints if c["status"] in ("open", "in_progress"))
    open_brk = sum(1 for b in breakdowns if b["status"] != "resolved")
    resolved_cmp = sum(1 for c in complaints if c["status"] in ("resolved", "closed"))
    critical = sum(1 for c in complaints if c["priority"] == "critical" and c["status"] in ("open", "in_progress"))
    kpis = [[open_cmp, "Open complaints"], [open_brk, "Active breakdowns"],
            [resolved_cmp, "Resolved complaints"], [critical, "Critical (open)"]]
    kpi_cells = []
    for num, lab in kpis:
        inner = Table([[Paragraph(f'<font size="18"><b>{num}</b></font>', H1),
                        Paragraph(f'<font size="8" color="#FFFFFF">{lab.upper()}</font>', SUB)]],
                      colWidths=[44 * mm])
        inner.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), BRAND),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("ROUNDEDCORNERS", [6, 6, 6, 6]),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ]))
        kpi_cells.append(inner)
    kpi_row = Table([kpi_cells], colWidths=[46 * mm] * 4)
    kpi_row.setStyle(TableStyle([
        ("LEFTPADDING", (0, 0), (-1, -1), 2), ("RIGHTPADDING", (0, 0), (-1, -1), 2),
    ]))
    story.append(kpi_row)
    story.append(Spacer(1, 6))

    # monthly bar chart
    story.append(Paragraph("Monthly complaint volume (last 6 months)", H2))
    if monthly:
        months = [m["month"][5:7] + "/" + m["month"][2:4] for m in monthly]
        counts = [m["n"] for m in monthly]
        mx = max(counts) or 1
        from reportlab.graphics.shapes import Drawing, Rect, String
        from reportlab.graphics import renderPDF
        W = 190 * mm
        H = 60 * mm
        d = Drawing(W, H)
        n = len(months)
        slot = W / n
        bar_w = slot * 0.5
        for i, cnt in enumerate(counts):
            x = (i * slot) + (slot - bar_w) / 2
            bh = (cnt / mx) * (H - 24 * mm)
            d.add(Rect(x, 12 * mm, bar_w, bh, fillColor=HexColor("#14B8A6"), strokeColor=None, rx=1.5))
            d.add(String(x + bar_w / 2, 6 * mm, months[i], fontSize=7, fillColor=INK, textAnchor="middle"))
            d.add(String(x + bar_w / 2, 12 * mm + bh + 2 * mm, str(cnt), fontSize=8, fillColor=INK, textAnchor="middle"))
        story.append(d)
    else:
        story.append(Paragraph("No complaint data in the last 6 months.", BODY))

    # status tables
    story.append(Paragraph("Complaints by status", H2))
    if by_status_cmp:
        rows = [[status_cell(s), Paragraph(str(n), BODY)] for s, n in by_status_cmp]
        t = Table(rows, colWidths=[30 * mm, 20 * mm])
        t.setStyle(_style_basic())
        story.append(t)
    story.append(Paragraph("Breakdowns by status", H2))
    if by_status_brk:
        rows = [[status_cell(s), Paragraph(str(n), BODY)] for s, n in by_status_brk]
        t = Table(rows, colWidths=[30 * mm, 20 * mm])
        t.setStyle(_style_basic())
        story.append(t)

    story.append(Paragraph("Most problem-prone equipment", H2))
    if top_equipment:
        rows = []
        for i, (name, n) in enumerate(top_equipment, 1):
            rows.append([Paragraph(str(i), BODY), Paragraph(name, BODY),
                         Paragraph(f'<b>{n}</b> faults', BODY)])
        t = Table(rows, colWidths=[12 * mm, None, 30 * mm])
        t.setStyle(_style_basic(add_header=True, header=["#", "Equipment", "Faults"]))
        story.append(t)
    else:
        story.append(Paragraph("No equipment data.", BODY))

    doc.build(story)
    return buf.getvalue()


def _style_basic(add_header=False, header=None):
    s = [
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, BG]),
        ("GRID", (0, 0), (-1, -1), 0.4, LINE),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]
    if add_header and header:
        s.append(("BACKGROUND", (0, 0), (-1, 0), BRAND))
        s.append(("TEXTCOLOR", (0, 0), (-1, 0), colors.white))
    return s
